name = "babel-fish-ws"
main = "src/worker.js"
compatibility_date = "2024-04-13"
workers_dev = true

[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]
