name = "babel-fish-ws"
main = "src/worker.js"
compatibility_date = "2024-04-13"
workers_dev = true

[[durable_objects.bindings]]
name = "chats"
class_name = "Chat"

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "WebSocketHibernationServer", to = "Chat" }]
